### PR TITLE
PL app translation

### PR DESCRIPTION
**Pull request by lpala**
Added PL app translation file
Tweaked microbiologist description

### CODE REVIEW

**Comment by lpala** [comment]
there are still two translations missing but I'm not sure what they refer to and I couldnt find them in the app

  "friend": "Friend",
  "grudge": "Grudge",

**Comment by pablogfb** [comment]
They are at the bonus points section of each character: Friend: 3(stars) if Counselor is in your BC and Scapes. Please add them

**Comment by lpala** [comment]
Of course. Somehow I've overlooked them.
I think I've added tweaks and added them do pull request.

By the way - in polish version Counselor is only 2 stars when being your side character.  Is there a difference between version or some kind of mistake on your side ?

**Comment by pablogfb** [comment]
> Of course. Somehow I've overlooked them. I think I've added tweaks and added them do pull request.
> 
> By the way - in polish version Counselor is only 2 stars when being your side character. Is there a difference between version or some kind of mistake on your side ?

Well, probably it is an update from the live rulebook. I'll check

**Pull request merged**
